# Generated by Django 5.0.6 on 2024-05-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Requirements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_uz", models.CharField(max_length=255)),
                ("title_ru", models.CharField(max_length=255)),
                ("annotation_uz", models.CharField(max_length=255)),
                ("annotation_ru", models.CharField(max_length=255)),
                ("description_uz", models.TextField()),
                ("description_ru", models.TextField()),
                ("problem_uz", models.CharField(max_length=255)),
                ("problem_ru", models.CharField(max_length=255)),
                ("solution_uz", models.CharField(max_length=255)),
                ("solution_ru", models.CharField(max_length=255)),
                ("learned_uz", models.CharField(max_length=255)),
                ("learned_ru", models.CharField(max_length=255)),
                ("analysis_uz", models.CharField(max_length=255)),
                ("analysis_ru", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Requirement",
                "verbose_name_plural": "Requirements",
                "db_table": "requirements",
            },
        ),
    ]
